### ISSUE TITLE
Autoname with options

### ISSUE THREAD

**Issue by zfengg** [ckf42/shdl#7]
Features:
- For the `{title}`, provide some more options:
  1. replace space with underline
  2. Make word into Camel case, e.g. `hello` ➡️ `Hello`. Then concentrating all the words to make the whole title a Camel case (like a variable name).
  3. ...
- Get the last names of the authors
- ...

**Comment by ckf42** [comment]
Don't have a good idea on how to do this. May need to implement each option on demand, or write an input parser for flexible format extension. Closing this for now.
